const api = "/api/v1/conversations";
let current = null;
let poller = null;
const rolePalette = { chatter:"#d7f578", critic:"#ff997d", moderator:"#82d8ff", evaluator:"#bda5ff", practical_engineer:"#f4c66f", synthesizer:"#77e0bd", listener:"#ee98d3", domain_expert:"#8fbbff", rational_analyst:"#c4d3e3", mediator:"#ffa9bc", visionary:"#c4a0ff", constraint_planner:"#e3bb78", contrarian:"#fa897e", explorer:"#9be0c2", order:"#90d7ba", master:"#fff" };
const initials = role => role.split("_").map(word => word[0]).join("").slice(0,2).toUpperCase();
const human = value => value.replaceAll("_", " ");
const time = value => new Intl.DateTimeFormat(undefined,{hour:"numeric",minute:"2-digit"}).format(new Date(value));
const escape = value => String(value || "").replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;",'"':"&quot;"}[char]));

async function request(path, options = {}) { const response = await fetch(`${api}${path}`, {headers:{"Content-Type":"application/json"}, ...options}); if (!response.ok) { const detail = await response.text(); throw new Error(`API returned ${response.status}${detail ? `: ${detail}` : ""}`); } return response.json(); }
function setConnection(online) { document.querySelector(".connection").classList.toggle("online", online); document.querySelector("#connection-label").textContent = online ? "API connected" : "Offline"; }
function activatePoller() { clearInterval(poller); if (current?.status === "running") poller = setInterval(() => load(current.id), 1800); }

async function load(id) { try { current = await request(`/${id}`); render(); setConnection(true); activatePoller(); } catch (error) { setConnection(false); console.error(error); } }
function render() {
  document.querySelector("#empty-state").classList.add("hidden"); document.querySelector("#workspace").classList.remove("hidden");
  document.querySelector("#session-topic").textContent = current.topic;
  document.querySelector("#context-goal").textContent = current.shared_context.goal;
  const status = document.querySelector("#status-pill"); status.textContent = current.status; status.className = `status-pill ${current.status}`;
  document.querySelector("#round-label").textContent = `Round ${current.current_round}`;
  document.querySelector("#agent-count").textContent = current.agents.filter(agent => agent.status === "active").length;
  const run = document.querySelector("#run-button"), stop = document.querySelector("#stop-button");
  run.classList.toggle("hidden", current.status !== "draft"); stop.classList.toggle("hidden", current.status !== "running");
  renderMetrics(); renderAgents(); renderTimeline(); renderEvaluation(); renderChanges();
  document.querySelector("#constraint-list").innerHTML = current.constraints.map(item => `<span class="constraint">${escape(item)}</span>`).join("") || '<span class="muted">No constraints set</span>';
}
function renderMetrics() { const cards = [["Round",current.current_round,"of " + current.runtime.max_rounds],["Contributions",current.exchanges.length,"across the room"],["Health checks",current.evaluations.length,"evaluator signals"],["Team changes",current.replacements.length,current.replacements.length ? "adaptive shifts" : "team stable"],["Model calls",current.usage.total.calls,((current.usage.total.input_tokens+current.usage.total.output_tokens)/1000).toFixed(1)+"k tokens · "+((current.usage.by_purpose.evaluation?.calls||0)+(current.usage.by_purpose.diversity?.calls||0))+" audit calls"]]; document.querySelector("#metrics").innerHTML = cards.map(([label,value,detail]) => `<article class="metric"><p>${label}</p><strong>${value}</strong><span>${detail}</span></article>`).join(""); }
function renderAgents() { document.querySelector("#agent-list").innerHTML = current.agents.map(agent => { const color = rolePalette[agent.role] || "#c7ccd8"; return `<article class="agent ${agent.status === "replaced" ? "replaced" : ""}" style="--role:${color}"><div class="avatar">${initials(agent.role)}</div><div class="agent-meta"><div class="agent-name">${human(agent.role)}</div><div class="agent-personality">${escape(agent.personality)}</div>${agent.perspective ? `<div class="agent-personality">Defends: ${escape(agent.perspective)}</div>` : ""}</div><span class="agent-score">${Math.round(agent.contribution_score * 100)}%</span><i class="agent-status"></i></article>`; }).join(""); }
function renderTimeline() { const items = [...current.exchanges.map(item => ({...item, kind:"exchange"})), ...current.evaluations.map(item => ({...item, kind:"evaluation"})), ...current.replacements.map(item => ({...item, kind:"replacement"}))].sort((a,b) => new Date(a.created_at)-new Date(b.created_at)); const timeline = document.querySelector("#timeline"); if (!items.length) { timeline.innerHTML = '<p class="muted">The room is assembled. Start the session when you are ready.</p>'; return; } timeline.innerHTML = items.map(item => { if(item.kind === "exchange") { const color=rolePalette[item.role] || "#ccc"; return `<article class="event" style="--role:${color}"><i class="event-dot"></i><div class="event-meta"><b>${human(item.role)}</b><span>Round ${item.round_number} · ${time(item.created_at)}</span></div><p class="event-message">${escape(item.content)}</p><div class="event-scores"><span>Contribution ${Math.round(item.contribution_score*100)}%</span><span>Novelty ${Math.round(item.novelty_score*100)}%</span></div></article>`; } if(item.kind === "evaluation") return `<article class="event"><i class="event-dot"></i><div class="event-system"><strong>Evaluator · ${human(item.recommendation)}</strong><br>${escape(item.rationale)}</div></article>`; return `<article class="event"><i class="event-dot"></i><div class="event-system"><strong>Team adaptation</strong><br>${human(item.removed_role)} made way for ${human(item.added_role)} · ${escape(item.reason)}</div></article>`; }).join(""); timeline.scrollTop = timeline.scrollHeight; }
function renderEvaluation() { const item = current.evaluations[current.evaluations.length - 1], target = document.querySelector("#evaluation-content"); if(!item) { target.innerHTML='<p class="muted">The evaluator will check the team after its first interval.</p>'; return; } const metrics=[["Progress",item.progress_score],["Coherence",item.coherence_score],["Novelty",item.novelty_score],["Redundancy",item.redundancy_score]]; target.innerHTML=`<div class="health-grid">${metrics.map(([label,value])=>`<div class="health-item"><p>${label}</p><b>${Math.round(value*100)}%</b><div class="bar"><i style="width:${value*100}%"></i></div></div>`).join("")}</div><p class="recommendation">${human(item.recommendation)} · ${escape(item.rationale)}</p>`; }
function renderChanges() { const target = document.querySelector("#change-list"); if(!current.replacements.length){target.innerHTML='<p class="muted">No changes to the roster yet.</p>';return;} target.innerHTML=current.replacements.slice().reverse().map(item=>`<div class="change"><span class="change-icon">↺</span><p><b>${human(item.removed_role)}</b> → <b>${human(item.added_role)}</b><br><small>${escape(item.reason)} · Round ${item.round_number}</small></p></div>`).join(""); }
document.querySelector("#new-session-form").addEventListener("submit", async event => { event.preventDefault(); const form=event.currentTarget, button=form.querySelector("button"); button.disabled=true; button.textContent="Creating…"; try { const topic=document.querySelector("#topic").value.trim(), constraints=document.querySelector("#constraints").value.split(",").map(value=>value.trim()).filter(Boolean); current=await request("",{method:"POST",body:JSON.stringify({topic,constraints,auto_start:false})}); render(); setConnection(true); form.reset(); } catch(error) { alert(`Could not create the workspace. ${error.message}`); console.error(error); } finally { button.disabled=false; button.innerHTML="<span>+</span> Create workspace"; } });
document.querySelector("#run-button").addEventListener("click", async () => { try { current=await request(`/${current.id}/start`,{method:"POST"}); render(); activatePoller(); } catch(error) { alert("Could not start the session."); } });
document.querySelector("#stop-button").addEventListener("click", async () => { try { current=await request(`/${current.id}/stop`,{method:"POST"}); render(); activatePoller(); } catch(error) { alert("Could not stop the session."); } });
(async () => { try { const conversations=await request(""); setConnection(true); if(conversations.length) load(conversations[0].id); } catch(error) { setConnection(false); } })();
